on: push
jobs:
  build:
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.ruby }}/
          tags: ghcr.io/unasuke/distroless-ruby:${{ matrix.ruby }}
          push: true
